sudo: false
language: android

android:
  components:
    - android-23
    - build-tools-23.0.2
    - build-tools-21.1.2

env:
  # TERM=dumb : For Gradle build output
  - TERM=dumb

before_script:
#  - cd app

script:
  # Build all gradle-based Android projects
  - ./gradlew build
